### ISSUE TITLE
Unable to persist data to Jira server.

### ISSUE THREAD

**Issue by orville94Bailey** [danshumaker/jira-cli#15]
I have been able to get this project set up and working so that I can pull info from my org's jira server instance. I have been unable to use this tool to persist any data back to the server. I've tried worklogs, comments, and editing fields. I'm being told that I should have permissions to updated via the api. Has this been reported before?

**Comment by mikhaili** [comment]
Can u run with you command with -v  param (jira create -v)

**Comment by mikhaili** [comment]
> I have been able to get this project set up and working so that I can pull info from my org's jira server instance. I have been unable to use this tool to persist any data back to the server. I've tried worklogs, comments, and editing fields. I'm being told that I should have permissions to updated via the api. Has this been reported before?

Can u run with you command with -v param (jira create -v)

**Comment by danshumaker** [comment]
@orville94Bailey Usually it's because of bad values inside the ~/.jira-cli/config.json file that cause issues.   The config.json file can be in several locations: the current directory or the home directory.
![inside-jira-cli-config](https://user-images.githubusercontent.com/358833/79074656-a5c37480-7cbb-11ea-90aa-3e4403c75e92.png)

Three things you can check inside your config.json file that might cause issue creation issues.
1) The project prefix might not be set correctly.  Manually edit the json file to set it to the correct value for your project.
2) Your token is not set correctly.  This value is tokenized from your password and should not be manually entered but only entered on the prompt.  Also note that three failed attempts at logging in will cause that thing (any tool/browser not just jira-cli) to be blocked.
3) The options, if not set correctly will cause jira tickets to not be able to be transitioned.  On our projects we changed the workflow a little and so I had to manually edit this file accordingly.

Let me know if that helps.

**Comment by danshumaker** [comment]
Oh yeah, and the custom fields  in your project will be different on every project so it's best to take those out when you first start on a project (jira config).

**Comment by orville94Bailey** [comment]
I know that a lot of customization has been done to our workflows. I will see if I can work through updating the config as you mentioned to get it to work.

**Comment by orville94Bailey** [comment]
I have decided against trying to get some of the higher level commands to work. Instead I'm trying to get ``` jira mark ``` to work. Using it I am able to see the transitions available for the issue supplied when entering the numeric transition ID I get a messages saying that the issue has been marked with the transition but I do not see that move being reflected anywhere.

**Comment by danielgombert** [comment]
> I have decided against trying to get some of the higher level commands to work. Instead I'm trying to get `jira mark` to work. Using it I am able to see the transitions available for the issue supplied when entering the numeric transition ID I get a messages saying that the issue has been marked with the transition but I do not see that move being reflected anywhere.

@orville94Bailey  - I found I had to do use the name  of the transition rather than the numeric value - for example *Done*.  However, if I wrapped it in quotes like *"Done"*, it would fail.

**Comment by danshumaker** [comment]
@orville94Bailey I also use the `jira mark` command when in doubt for the same reason you do - more precise and verbose.  However you should see the new status when you do a `jira show XXXX` on the ticket.  If not then something is wrong.

**Comment by orville94Bailey** [comment]
@danielgombert You had to reference the name of the transition using `jira mark`. Is that correct? I am unable to enter text when prompted for the transition.

**Comment by danielgombert** [comment]
@orville94Bailey  - I stand corrected.  When I use `jira done` and then use the `-r` switch to enter the resolution, that is when I need to enter text.  I just tried `jira mark` and the list of choices came up.   First, I tried typing 'Done', and I was able to type out the word "Done", but it failed quietly and showed me the list of choices again.  Then I entered the transition #, and it set the new status correctly.  I think what @danshumaker commented a week ago (while not necessarily helpful in solving the issue) is correct.

**Comment by orville94Bailey** [comment]
@danshumaker I have been unsuccessful in getting `jira mark` to make changes to issue status. No errors are reported when attempting to use it.

I have been able to use postman to make the http calls to move things and that is working as expected. Is there something that would prevent this from working if sites are not using a public CA?

**Comment by danshumaker** [comment]
@orville94Bailey Did you try typing in the number instead of the text?

**Comment by orville94Bailey** [comment]
@danshumaker 
When using `jira mark` I am providing a numerical Id that is being shown from jira-cli. I have been poking around in the source to inspect the response from the server but I am not seeing anything obvious.

**Comment by orville94Bailey** [comment]
I believe I've found the root cause. When setting up jira-cli I neglected to specify `http` or `https` on my jira endpoint. I believe this was causing something strange to happen with a redirect. It is still strange to me that superagent did not see a failing request. I have updated my config values to explicitly use https and it's working now.
