### ISSUE TITLE
Suggestion: package.json

### ISSUE THREAD

**Issue by mikhaili** [danshumaker/jira-cli#16]
Hey I would like to add to project:
    "start": "npm run global",
    "dev": "node bin/jira.js",
    "global": "npm i -g && jira",
    "clean": "rimraf -rf ./.jira-cli"

**Comment by danshumaker** [comment]
Sounds great!

**Comment by mikhaili** [comment]
> Sounds great!
How can I push the changes?

**Comment by mikhaili** [comment]
> Sounds great!

How can I push the changes?

**Comment by danshumaker** [comment]
@mikhaili Submit a pull request and I'll merge it!

**Comment by mikhaili** [comment]
Please add me as a collaborator, I also have a branch with config file improvements
