### ISSUE TITLE
Q: es2015 migration

### ISSUE THREAD

**Issue by mikhaili** [danshumaker/jira-cli#21]
Hey do u want migrate to es2015 instead of requirejs?
1. babel have plugin  [babel-plugin-transform-amd-to-commonjs] so the migration will be very easy
2. Easy to create tests and test the code
3. Use of imports or require

**Comment by danshumaker** [comment]
Thanks a ton for your help on everything @mikhaili . I made you a collaborator and merged your es2015 MR.  The other ones have conflicts I believe.
