### ISSUE TITLE
TypeError running jira config in fresh install

### ISSUE THREAD

**Issue by luvacu** [danshumaker/jira-cli#27]
After installing, when I run `jira config` to provide the URL and credentials, I get the following error:

```bash
$ jira config
/Users/luis/.nvm/versions/node/v13.13.0/lib/node_modules/jira-cli/bin/jira.js:52
  host: config.authNew.host,
                       ^

TypeError: Cannot read property 'host' of undefined
    at Object.<anonymous> (/Users/luis/.nvm/versions/node/v13.13.0/lib/node_modules/jira-cli/bin/jira.js:52:24)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:972:32)
    at Function.Module._load (internal/modules/cjs/loader.js:872:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

Any ideas? Thank you!

**Comment by mikhaili** [comment]
Hey, 
yes it already fixed in source code
@danshumaker can u please publish new version with fix?

**Comment by danshumaker** [comment]
Yep , will roll a new release now.

**Comment by danshumaker** [comment]
@luvacu Try this one https://registry.npmjs.org/jira-cli/-/jira-cli-2.1.0.tgz
and let us know how it goes. Thanks!

**Comment by luvacu** [comment]
@danshumaker @mikhaili You are amazing, thank you!! The issue with `jira config` is gone.
However, now I am not able to authenticate the requests since my Atlassian account is managed by Google (Sign in with Google). For example, if I run `jira edit JRA-123` I get a 401 error.
```shell
Error: cannot GET //rest/api/2/issue/JRA-123/editmeta (401)
```
I tried pasting my Atlassian API token in `.jira-cli/config.json` but it didn't work.
```json
"auth": {
  "url": "http://xxx.atlassian.net/",
  "user": "user@acme.com",
  "token": "API_TOKEN"
},
```
I guess API tokens are not supported, right?

**Comment by mikhaili** [comment]
Hey, 
1. The token generated from Base64(username:pass) please do not modify it.
u can clean config  (jira config -c) and jira config
2. Please try jira ls or jira show JRA-123 does it work?

**Comment by luvacu** [comment]
I cleared the config and set it again, putting the API token as the password and it did work!! Thank you so much for your help! 🔝

**Comment by mikhaili** [comment]
@luvacu Great to hear it
Do u know which functionality you will use?
Suggestions are welcome !!!

**Comment by luvacu** [comment]
Yes, I'll try to automate the creation of Android & iOS subtasks for our user stories, then add the Android/iOS component and set their status to To-Do o Selected for development. Let's see how it goes!

**Comment by mikhaili** [comment]
Ok update if u need any help. (JIRA API libraries: jira-client, jira-connector)
