### ISSUE TITLE
Basic authentication is deprecated

### ISSUE THREAD

**Issue by kahoot-karl** [danshumaker/jira-cli#30]
I can't use the tool due to this error message:

```
Basic authentication with passwords is deprecated.  For more information, see: https://confluence.atlassian.com/cloud/deprecation-of-basic-authentication-with-passwords-for-jira-and-confluence-apis-972355348.html\n
```

**Comment by lmmattr** [comment]
It looks like API tokens should be a decent replacement: https://developer.atlassian.com/cloud/jira/platform/basic-auth-for-rest-apis/

**Comment by srl295** [comment]
@kahoot-karl instead of using a password, can you try creating an API key at https://id.atlassian.com/manage-profile/security/api-tokens# and using that? worked for me (I didn't see that message, but I have 2FA and passwords aren't usable)

**Comment by chipbite** [comment]
Just installed this tool via npm and configured as in the readme on the front page and I get a stacktrace the length of the china wall when trying a command, where atlassian repeats that "Basic authentication with passwords is deprecated." 

It seems the instructions for configuration need to be updated, and maybe something in this tool itself?

**Comment by srl295** [comment]
> Just installed this tool via npm and configured as in the readme on the front page here on github and I get a stacktrace the length of the china wall when trying a command, where atlassian repeats that "Basic authentication with passwords is deprecated." 
> 
> 
> 
> It seems the instructions for configuration need to be updated, and maybe something in this tool itself?

@chipbite I had the same, please try my instructions immediately above

**Comment by danshumaker** [comment]
@chipbite ,    @srl295 is correct, you need an api token and that is your "password" so to speak. I'm very sorry for the outdated README.  Unfortunately I don't have a jira instance to test against right now, but if I can find a free version I'll test and verify and update the README asap.

**Comment by chipbite** [comment]
Hi! Thanks alot for your quick replies.
So I have used the atlassian API tokens with a few of my own scripts and I created a new one for use in this, but strangely I cannot get it to work.
Something else might be amiss. 
I tried:
- reset config and re-entered user (email) and the token as password.
- editing the config directly.

I tried showing an issue I know exist, but no dice. 

- If I try with the token in the password field in the config, I get the "basic auth is not supported message"
- If I put the token at the end of the user string with a colon delimiter, I get "Issue does not exist or you do not have permission to see it.", which is odd since I am viewing it via the normal web UI.

If I do the call via curl and the token, it works and I get the page.

    curl -v https://COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID> --user me@COMPANY.com:TOKEN

Not sure what the issue could be.

BR! /marcus

**Comment by dalewking** [comment]
Basically the username and password go into the URL, not in authentication headers. So:

https://me:COMPANY.com:TOKEN@COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID>

**Comment by chipbite** [comment]
Thanks @dalewking. Putting l/p in URL works for jira config. 
Meaning, working config:
```
	https://me@COMPANY.com:TOKEN@COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID>
	Username: me@COMPANY.com
	Password: TOKEN
```
Not sure if u/pwd is redundant, it seems to work anyway.

So, this works:
`curl -v https://COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID> --user me@COMPANY.com:TOKEN`

So, using l/p in URL, I get these results: (1) Fails in curl, (2) works in browser and (3) works in jira cli config, yay! 🎉

So, oddly (to me), this does NOT work in curl, but in a browser:
```
// Not working:
curl https://me@COMPANY.com:TOKEN@COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID>
// BUT this works in a browser, e g chrome:
     https://me@COMPANY.com:TOKEN@COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID>
```

And finally, again, using l/p in URL **works** for jira config:

```
jira config -c

jira config
	Jira URL: null
	https://me@COMPANY.com:TOKEN@COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID>
	Username: me@COMPANY.com
	Password: TOKEN
```

Phew!
Thanks alot for the pointers.

BR! /mawi

**Comment by dalewking** [comment]
> curl https://me@COMPANY.com:TOKEN@COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID>

For curl use the username command line parameter to pass the username:token combination

And yes the username and password fields in jira config are redundant when you put them in the url.

**Comment by chipbite** [comment]
> > curl https://me@COMPANY.com:TOKEN@COMPANY.atlassian.net/rest/api/latest/issue/
> 
> For curl use the username command line parameter to pass the username:token combination

Agreed, that worked from the start. From my earlier comment:

>> If I do the call via curl and the token, it works and I get the page.
>> `curl -v https://COMPANY.atlassian.net/rest/api/latest/issue/<ISSUEID> --user me@COMPANY.com:TOKEN`

> And yes the username and password fields in jira config are redundant when you put them in the url.

OK, good to know.

Again, thanks!
