### ISSUE TITLE
Commands handle config.auth.url differently

### ISSUE THREAD

**Issue by willbowdi** [danshumaker/jira-cli#38]
Some commands add a forward slash to the auth.url provided when configuring the url but not all of them.

Take `jira worklog <issue>` for example, this does not add a forward slash so when I set the url (we use Jira server) to our address I need to add the last forward slash for this to work i.e. set URL as 'https://company.com/jira/' which results in this endpoint https://company.com/jira/rest/api/latest/{issue}/worklog.

However, when using `jira edit <issue>` this adds in a backslash so the url that is generated with the above config results in https://company.com/jira//rest/api/2/issue/{issue}/editmeta.

**Comment by willbowdi** [comment]
Doing a quick search of the repo, it looks like the following files are the odd ones out are:
lib/jira/link.js
lib/jira/edit.js

Both of them adding in a forward slash where others do not.

**Comment by mikhaili** [comment]
> Doing a quick search of the repo, it looks like the following files are the odd ones out are:
> 
> * lib/jira/link.js
> * lib/jira/edit.js
> 
> Both of them adding in a forward slash where others do not.

Thanx for help, PR opened
