### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by perceptron007** [danshumaker/jira-cli#4]
Right now installing the project gives a lot of deprecated packages warning.
Can we update some packages if possible? Willing to contribute if you need help.

**Comment by danshumaker** [comment]
Hi @perceptron007 , I'd love help.  I simply have no time lately.  I'd love to update the tool as well.  #1 
Submit a PR and I'd be glad to check it out and merge.

**Comment by danshumaker** [comment]
@perceptron007 Some packages have been updated.
