### ISSUE TITLE
Unable to create issues

### ISSUE THREAD

**Issue by O5ten** [danshumaker/jira-cli#5]
I have ran `jira config` successfully and now have an accesstoken in my ~/.jira-cli/config.json

I am able to list my issues and run arbitrary JQL. 
The things i can't do is create new issues and edit them. 

Running `jira new --verbose` yields a 404 not found. 

```
   { Error: got 400 response
       at Response.toError (/home/my-username/tools/nodejs/lib/node_modules/jira-cli/node_modules/superagent/lib/node/response.js:100:13)
       at Response.setStatusProperties (/home/my-username/tools/nodejs/lib/node_modules/jira-cli/node_modules/superagent/lib/node/response.js:179:12)
       at new Response (/home/my-username/tools/nodejs/lib/node_modules/jira-cli/node_modules/superagent/lib/node/response.js:40:8)
       at IncomingMessage.<anonymous> (/home/my-username/tools/nodejs/lib/node_modules/jira-cli/node_modules/superagent/lib/node/index.js:712:22)
       at IncomingMessage.emit (events.js:194:15)
       at endReadableNT (_stream_readable.js:1103:12)
       at process._tickCallback (internal/process/next_tick.js:63:19) status: 400 },
```
That's a bad request from the default behavior of jira-cli. 

Now, i checked the output more in detail and found a payload that is attempting to send 

```json
{ 
   "fields":{ 
      "project":{ 
         "id":"18100"
      },
      "issuetype":{ 
         "id":10002
      },
      "summary":"Test Testing Tested",
      "components":[ 
         { 
            "id":"23214"
         },
         { 
            "id":"23280"
         }
      ],
      "reporter":{ 
         "id":"mikael.ostberg"
      },
      "customfield_11801":{ 
         "id":"14628"
      }
   }
}
```

Notice the 
```json
      "reporter":{ 
         "id":"mikael.ostberg"
      },
```

Now the [JIRA API Docs ](https://docs.atlassian.com/software/jira/docs/api/REST/8.5.0/#api/2/issue-createIssue) clearly states that the field for reporter should use `name` instead of `id` as reporter key. And if i set it using defaults to use name then i can create issues. However, editing them suffers from the same problem. I have a strong sensation that [this line](https://github.com/danshumaker/jira-cli/blob/0624e3512b1eae556c0092e49efb1c9b3e7748cd/lib/jira/new.js#L146) has something to do with it.

**Comment by O5ten** [comment]
@danshumaker is this a dead project? : )

**Comment by danshumaker** [comment]
Hi O5ten , i use this tool every day.  So it’s not dead in that respect. My time is limited, so there is that issue. I did update the version recently. Are you using the latest version?

**Comment by danshumaker** [comment]
It seems that the api has been updated

**Comment by O5ten** [comment]
I installed it last friday, so i guess i am using the latest version. 
And i fully respect the matter of time when it comes to these projects. 

If you need help with fixing this, then feel free to ask for pull requests. I just might fix it myself.

**Comment by danshumaker** [comment]
Pull requests are always welcome

**Comment by danshumaker** [comment]
@O5ten Try again with 1.5.1
