### ISSUE TITLE
show custom field in `jira epic list EPIC-ID`

### ISSUE THREAD

**Issue by hanshasselberg** [danshumaker/jira-cli#67]
Hello,

thanks for this great tool! This is exactly what I have been looking for. Right now I am trying to show an epic with its tasks. These tasks have a custom field `Story point estimate`. I cannot figure out how to show the story points...

```
jira epic list HCS-3055 --plain --columns key,summary,status,story-point-estimate
```

This is what I thought should work after reading the information in the custom field PR, but it doesn't.

**Comment by palashkulsh** [comment]
@i0rek [jira-cmd](https://github.com/palashkulsh/jira-cmd) is actively maintained version
for this usecase you can use jira jql "<your jql>" -j 1 to get json format of jira in will have all the custom fields which you can use

**Comment by hanshasselberg** [comment]
@palashkulsh thank you, that solved my problem!
