### ISSUE TITLE
Can this work with Google Authenticate?

### ISSUE THREAD

**Issue by colinjcahill** [danshumaker/jira-cli#9]
I am getting 401s when I try to `jira config` with a company account that is authenticated through Google.

As expected, the combination of my email and password don't seem to work (although no login error shows up).

I then updated the config.json based on a custom API token from /id.atlassian.com/manage/api-tokens, and this also doesn't work.  Any other tricks to try, or is this just not supported?

**Comment by danshumaker** [comment]
HI @colinjcahill , I too use it for work and am authenticated through google.  When jira-cli prompts you for a password, you do need to enter in your api token that is created here: https://id.atlassian.com/manage/api-tokens  (Create API Token)  - as you mentioned.
Several blockers could be if you are using your email password, or have had three or more failed login attempts, or have not generated an api key yet, or if you have 2 factor authentication turned on.

If you've had three or more failed attempts, then you need to clear the "blocked" status via the attlassian admin ui.

I hope that helps. Let me know how it goes.

**Comment by colinjcahill** [comment]
nice, that worked!  Thanks @danshumaker
